# The URL the site will be built for
base_url = "https://pdlloyd.com"
title = "@pdlloyd"

#theme = "terminimal"
theme = "apollo"

# Whether to automatically compile all Sass files in the sass directory.
# Required for Terminimal.
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# The theme supports feeds (RSS and ATOM)
generate_feed = true

# Use `rss.xml` for RSS feeds and `atom.xml` for ATOM.
feed_filename = "atom.xml"

favicon = "/icon/favicon.png"
favicon_mimetype = "image/png"

minify_html = true

default_language = "en"

[markdown]
# Syntax highlighting
highlight_code = true
highlight_theme = "boron"

[extra]

theme = "toggle" # light, dark, auto, toggle

# Author name: when specified, modifies the default
# copyright text. Apart from author, it will
# contain current year and a link to the theme.
author = "Patrick D. Lloyd"

menu = [
    { name = "/blog", url = "/", weight = 1 },
    { name = "/projects", url = "/projects", weight = 2 },
    { name = "/about", url = "/about", weight = 3 },
]

 socials = [
     { name = "rss", url = "/atom.xml", icon = "rss" },
#     { name = "github", url = "https://github.com/not-matthias/", icon = "github" },
#     {name = "gitLab", url = "https://gitlab.com/pdlloyd", icon = "gitlab"},
 ]


# Whether to show links to earlier and later (aka. higher/lower) posts
# on each post page (defaults to true).
enable_post_view_navigation = true

# The text shown at the bottom of a post,
# before earlier/later post links.
# Defaults to "Thanks for reading! Read other posts?"
post_view_navigation_prompt = "Thanks for reading! Read other posts?"

